font_family      JetBrainsMono Nerd Font Mono
font_size        19

background_opacity 0.94
hide_window_decorations yes
confirm_os_window_close 0

cursor_shape underline
cursor_underline_thickness 2.0

foreground #cad3f5
background #24273a
selection_foreground #24273a
selection_background #f4dbd6

cursor #f4dbd6
cursor_text_color #24273a

color0  #494d64
color1  #ed8796
color2  #a6da95
color3  #eed49f
color4  #8aadf4
color5  #f5bde6
color6  #8bd5ca
color7  #b8c0e0
color8  #5b6078
color9  #ed8796
color10 #a6da95
color11 #eed49f
color12 #8aadf4
color13 #f5bde6
color14 #8bd5ca
color15 #a5adcb

map alt+left neighboring_window left
map alt+down neighboring_window down
map alt+up neighboring_window up
map alt+right neighboring_window right
map alt+enter toggle_fullscreen
