set -g default-terminal "screen-256color"

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

unbind %
bind '\' split-window -h -c '#{pane_current_path}'

unbind '"'
bind - split-window -v -c '#{pane_current_path}'

# new-window
bind c new-window -c '#{pane_current_path}'

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

# Copy vim motion
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind r 
# tmux source-file ~/.tmux.conf \;
bind r source-file ~/.tmux.conf


# Yazi config Image preview
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -g mouse on

# start from 1, not 0
set-option -g base-index 1
# re-index when closing windows
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'


set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato, mocha
set -g @plugin 'catppuccin/tmux#v2.1.2'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'


# open a note for billion $ idea
bind -r e split-window -h "nvim ~/Documents/git/scratch/notes_$(date +'%Y%m%d%H').md"
bind -r v split-window -h -c "#{pane_current_path}" "zsh -c 'nvim; exec zsh'"
bind -r o split-window -h "nvim ~/Documents/git/scratch/todo_$(date +'%y%m%d').md"


# Status bar config
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'xamut/tmux-weather'
set -g @catppuccin_window_status_style "basic"
set -g window-status-separator ""

set -g @catppuccin_window_current_text_color "#{@thm_surface_1}"
set -g @catppuccin_window_current_number_color "#{@thm_peach}"
set -g @catppuccin_window_current_text "#[bg=#{@thm_mantle}] #{b:pane_current_path}"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_number_color "#{@thm_lavender}"

set -g status-left-length 100
set -g status-position bottom
set -g status-interval 10
set -g status-right-length 200 
set -g status-right ""

##  --- Left Status (Session Name) ---
set -g status-left "#[bg=#{@thm_green},fg=#{@thm_crust}]#[reverse]#[noreverse] #S "

# Pomodoro
bind-key b command-prompt -p "Pomodoro (sessions [work break])" "run-shell '~/dotfiles/tmux/pomocmd.sh %%'"
bind-key 0 run-shell '~/dotfiles/tmux/pomodoro.sh stop'


## --- Right Status
# Toggle mode: username → todo → pomodoro
bind-key Tab run-shell "\
  mode=\$(tmux show-environment STATUS_MODE 2>/dev/null | cut -d= -f2); \
  case \$mode in \
    todo) tmux set-environment STATUS_MODE pomo ;; \
    pomo) tmux set-environment STATUS_MODE user ;; \
    *)    tmux set-environment STATUS_MODE todo ;; \
  esac; \
  tmux refresh-client -S"

# 0. Dynamic segment
set -ag status-right "#[fg=#{@thm_crust}]"
set -ag status-right "#[fg=#{@thm_fg},bg=default] #(bash ~/dotfiles/tmux/status_mode.sh) "

# 1. Weather & CPU (Catppuccin Style)
set -agF status-right "#{E:@catppuccin_status_weather}"
set -agF status-right "#{E:@catppuccin_status_cpu}"

# 2. Memory Pressure (Custom Logic)
set -ag status-right "#[bg=#{@thm_green},fg=#{@thm_crust}]#[reverse]█#[noreverse]󰘛 "
set -ag status-right "#[fg=#{@thm_fg},bg=#{@thm_mantle}] #(free -m | awk '/Mem:/ { printf(\"%.1f\", $3/$2*100) }')%% "

# 3. Clock
set -agF status-right "#[bg=#{@thm_green},fg=#{@thm_crust}]#[reverse]█#[noreverse]󰢗 "
set -agF status-right "#[fg=#{@thm_fg},bg=#{@thm_mantle}] %m/%d:%H "


set -g status-style bg=default
set -g status-bg default 

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g status-bg default
set -g status-style bg=default
